on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Chombo workflow
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: jrgparkinson/chombo-action@v1.4
      with:
        compile_opts: 'DIM=3'

    - name: Check Chombo install
      run: echo $CHOMBO_HOME
